# Generated by Django 5.0.2 on 2024-04-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='image',
            field=models.ImageField(default=1, upload_to='blog'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
