# Generated by Django 5.0.2 on 2024-02-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='finising',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
